feat: add assignee downstream in GitHub
spring-financial-group/jx-updatebot pull request #18
Opened 2024-11-12 13:25 UTC by GavinPJK

2024-11-12 14:27 UTC, Skisocks requested changes

2024-11-12 15:48 UTC, GavinPJK commented on pkg/cmd/pr/pr.go
> +}
Picking a recent example: https://github.com/spring-financial-group/mqube-income-service/commit/2912a037fe533cf3b8a7b959edb3276b2330716d

This is the release pipeline: https://tekton-dashboard.jx.mqube.build/#/namespaces/jx/pipelineruns/qube-income-service-main-release-xblqb?pipelineTask=from-build-pack

`PULL_BASE_SHA=2912a037fe533cf3b8a7b959edb3276b2330716d`

Running the command gives:
```
$ git show -s --format=%ae 2912a037fe533cf3b8a7b959edb3276b2330716d
zack.jagger@mqube.com
```
The git credentials are correct within the pipeline, afaict

2024-11-12 16:07 UTC, GavinPJK commented on pkg/cmd/pr/pr.go
> +	cmd.Flags().StringSliceVar(&o.GitHubAssignees, "github-assignee", []string{}, "list of authors to assign to downstream GitHub PRs")
Aha, gotcha. Then I guess we could have one of the following (using case as an example):

```
apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  pullRequestLabels:
    - updatebot
    - deps/mqube-product-service
  rules:
    - urls:
        - https://github.com/spring-financial-group/mqube-case-service
      changes:
        - regex:
            pattern: >
              <PackageReference Include="Mqube.ProductService.Client" Version="(.*?)" \/>
            files:
              - "**/*.csproj"
      reusePullRequest: true
      pullRequestAssignees:
        - GavinPJK
        - Skisocks
```
Or:

```
apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  pullRequestLabels:
    - updatebot
    - deps/mqube-product-service
  rules:
    - urls:
        - https://github.com/spring-financial-group/mqube-case-service
      changes:
        - regex:
            pattern: >
              <PackageReference Include="Mqube.ProductService.Client" Version="(.*?)" \/>
            files:
              - "**/*.csproj"
      reusePullRequest: true
      autoAssignDownstreamCommits: true
```
This work points to the latter being valuable to us but I could see value in the former, too

2024-11-14 15:53 UTC, Skisocks requested changes

2024-11-14 15:53 UTC, Skisocks commented on pkg/cmd/pr/pr.go
> +		o.PipelineCommitSha = os.Getenv("PULL_PULL_SHA")
Unfortunately I don't think this env var is actually populated in the release pipeline :S

2024-11-20 12:06 UTC, Skisocks requested changes

2024-11-20 12:06 UTC, Skisocks commented on pkg/cmd/pr/pr.go
> +				o.CommitMessage = fmt.Sprintf("from: %s\n", gitURL)
Not a fan of the nested ifs and else ifs. I don't like the way it was originally done so would be good refactor the original implementation :)

2024-11-20 12:06 UTC, Skisocks commented on pkg/cmd/pr/pr.go
> +	fmt.Println("Debug: Starting Run command...")
We should use the proper lpgger if you're plannign to keep these log lines

2024-11-20 12:06 UTC, Skisocks commented on pkg/cmd/pr/pr.go
>  	}
Same as above here with the nesting. We should refactor to pull out into specific functions.

Are the original tests for this command good?

2024-11-26 16:26 UTC, GavinPJK commented
@Skisocks - refactored Run() by stripping back inner logic, with functions doing the heavy lifting. Switched log output to use logger

2024-12-02 14:50 UTC, GavinPJK commented on pkg/cmd/pr/pr_test.go
> +}
Just running these commands won't work when testing, as they need commit info. Mocking them and checking test data works seems to be the best way to do it?

2024-12-02 15:19 UTC, GavinPJK commented on pkg/cmd/pr/pr.go
> +	}
Done

2025-01-22 15:58 UTC, merged